### ISSUE TITLE
Undefined symbol: `add_defined_function`

### ISSUE THREAD

**Issue by knightss27** [GooDeeJaY/foma-py#1]
Hi there!

I am working on a project that uses foma in Python, and saw you had created this library with the code from foma's own Github, and wanted to ask about an error I am encountering with both (considering the issues on the actual repo are rarely answered).

When using foma in my Python code, either after installing this package or using the file given in foma's repo, I find that I get:
```Traceback (most recent call last):
  File "/root/reconstruct/reconstruct.py", line 2, in <module>
    from foma import FST
  File "/usr/local/lib/python3.9/dist-packages/foma/__init__.py", line 111, in <module>
    foma_add_defined_function = foma.add_defined_function
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libfoma.so.0: undefined symbol: add_defined_function
```
I have installed `libfoma0` and `libfoma0-dev` and I can see that the Python code is clearly finding the shared object, however when I run `objdump -TC libfoma.so.0 | grep defined`, it is clear that there is no `add_defined_function` exposed as a method:

```
0000000000006130 g    DF .text  00000000000000c8  Base        add_defined
00000000000141f0 g    DF .text  00000000000000d9  Base        load_defined
0000000000013dc0 g    DF .text  00000000000000b8  Base        save_defined
0000000000005eb0 g    DF .text  000000000000000f  Base        defined_networks_init
0000000000005ec0 g    DF .text  000000000000000f  Base        defined_functions_init
```

I have found that a solution to have this work is to just comment out lines 111 and 112, along with the function `definef` of your `__init__.py` / `foma.py` as I am not currently using this in my program. I was wondering whether you have gotten this to work without the error, and if so how? Is it possible I am somehow on a wrong version of `libfoma`? Thank you for any help!

**Comment by Queztalcoatlus** [comment]
I am trying to use Foma in Python and found this solution as well. `definef` is not used anywhere in the repo. I am wondering what the purpose of the method is.

**Comment by jzr-supove** [comment]
Hello, sorry for the late reply, I faced this issue as well when I was using foma

I managed to resolve this issue by installing older version of `libfoma0` - 0.10.0

```
sudo apt-get install libfoma0=0.10.0+s305-3~focal1
```

https://github.com/mhulden/foma/issues/139
