### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by scott-parkhill** [GooDeeJaY/foma-py#2]
@GooDeeJAY We might very well be like the only people using this package lol. I have a question for you. We have forked the mhulden foma project with its python binding file in there. However, you have control over the pip package. For us, the `get_defined_function` functionality doesn't work as it can't find the symbol in the foma library `.so`, but also we're looking to add functionality to this overtime. Not sure how best to maintain this. We were planning on making PRs into the main foma project, but we were under the false impression that Mans was maintaining the pip package. Just wondering what you're thinking as it may impact how we go forward.

**Comment by jzr-supove** [comment]
Hello, sorry for the late reply, I remember facing the same `get_defined_function` problem, which I managed to solve by installing the older version of `libfoma0` - 0.10.0

Please, look at:
https://github.com/mhulden/foma/issues/139

Collaborations are welcome :) 
You can make PRs into this repo, I will try to keep the the pypi package updated
